# Generated by Django 5.1.7 on 2026-01-10 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodsafetyagencyinspection',
            name='dispensation_application',
            field=models.BooleanField(default=False, help_text='Dispensation application required'),
        ),
        migrations.AddField(
            model_name='foodsafetyagencyinspection',
            name='follow_up',
            field=models.BooleanField(default=False, help_text='Follow-up required'),
        ),
        migrations.AddField(
            model_name='foodsafetyagencyinspection',
            name='inspected',
            field=models.BooleanField(default=False, help_text='Was inspection conducted?'),
        ),
        migrations.AddField(
            model_name='foodsafetyagencyinspection',
            name='occurrence_report',
            field=models.BooleanField(default=False, help_text='Occurrence report required'),
        ),
        migrations.AddField(
            model_name='foodsafetyagencyinspection',
            name='town',
            field=models.CharField(blank=True, help_text='Town/location of inspection', max_length=100, null=True),
        ),
    ]
