# Generated by Django 5.1.7 on 2025-09-30 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodsafetyagencyinspection',
            name='additional_email',
            field=models.EmailField(blank=True, help_text='Additional email for this specific inspection group', max_length=254, null=True),
        ),
    ]
