# Generated by Django 5.1.7 on 2026-01-10 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_add_inspection_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodsafetyagencyinspection',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Link to Client record for file storage', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='main.client'),
        ),
    ]
