# Generated by Django 5.1.7 on 2025-08-30 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_shipment_client_reference_alter_shipment_claim_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspector', models.CharField(help_text='Inspector name (e.g., Cinga Ngongo)', max_length=100)),
                ('inspection_number', models.PositiveIntegerField(help_text='Sequential inspection number')),
                ('inspection_date', models.DateField(help_text='Date of inspection')),
                ('facility_client_name', models.CharField(help_text='Facility or client name', max_length=200)),
                ('town', models.CharField(blank=True, help_text='Town/location', max_length=100, null=True)),
                ('commodity', models.CharField(blank=True, help_text='Commodity type (e.g., RAW)', max_length=50, null=True)),
                ('product_name', models.CharField(blank=True, help_text='Product name (e.g., Mince, Mildwors)', max_length=100, null=True)),
                ('product_class', models.CharField(blank=True, help_text='Product class (e.g., Raw species sausage / wors)', max_length=100, null=True)),
                ('inspected', models.BooleanField(default=False, help_text='Was inspection conducted?')),
                ('sampled', models.BooleanField(default=False, help_text='Was sampling conducted?')),
                ('normal_hours', models.DecimalField(blank=True, decimal_places=1, help_text='Normal hours worked', max_digits=4, null=True)),
                ('kilometres_traveled', models.DecimalField(blank=True, decimal_places=1, help_text='Kilometres traveled', max_digits=6, null=True)),
                ('fat', models.BooleanField(default=False, help_text='Fat testing required')),
                ('protein', models.BooleanField(default=False, help_text='Protein testing required')),
                ('calcium', models.BooleanField(default=False, help_text='Calcium testing required')),
                ('dna', models.BooleanField(default=False, help_text='DNA testing required')),
                ('bought_sample_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount paid for sample', max_digits=8, null=True)),
                ('lab_used', models.CharField(blank=True, help_text='Laboratory used (e.g., Food Safety Laboratory)', max_length=100, null=True)),
                ('follow_up', models.BooleanField(default=False, help_text='Follow-up required')),
                ('occurrence_report', models.BooleanField(default=False, help_text='Occurrence report required')),
                ('dispensation_application', models.BooleanField(default=False, help_text='Dispensation application required')),
                ('comments', models.TextField(blank=True, help_text='Additional comments or notes', null=True)),
                ('uploaded', models.BooleanField(default=False, help_text='Files uploaded')),
                ('rfi_reference_number', models.CharField(blank=True, help_text='RFI reference number', max_length=100, null=True)),
                ('invoice_reference_number', models.CharField(blank=True, help_text='Invoice reference number', max_length=100, null=True)),
                ('lab_result_reference_number', models.CharField(blank=True, help_text='Lab result reference number', max_length=100, null=True)),
                ('re_test', models.BooleanField(default=False, help_text='Re-test required')),
                ('re_test_reference_number', models.CharField(blank=True, help_text='Re-test reference number', max_length=100, null=True)),
                ('verification_external_testing', models.BooleanField(default=False, help_text='Verification or external testing required')),
                ('compliance_document', models.CharField(blank=True, help_text='Compliance document reference', max_length=100, null=True)),
                ('direction_expiry_date', models.DateField(blank=True, help_text='Direction expiry date', null=True)),
                ('email', models.EmailField(blank=True, help_text='Primary email contact', max_length=254, null=True)),
                ('additional_email_1', models.EmailField(blank=True, help_text='Additional email 1', max_length=254, null=True)),
                ('additional_email_2', models.EmailField(blank=True, help_text='Additional email 2', max_length=254, null=True)),
                ('additional_email_3', models.EmailField(blank=True, help_text='Additional email 3', max_length=254, null=True)),
                ('additional_email_4', models.EmailField(blank=True, help_text='Additional email 4', max_length=254, null=True)),
                ('was_mail_sent', models.BooleanField(default=False, help_text='Was email sent?')),
                ('compiled_supporting_documents', models.CharField(blank=True, help_text='Compiled supporting documents', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Inspection',
                'verbose_name_plural': 'Inspections',
                'ordering': ['-inspection_date', '-inspection_number'],
            },
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='client',
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name'], 'verbose_name': 'Food Safety Agency Client', 'verbose_name_plural': 'Food Safety Agency Clients'},
        ),
        migrations.RemoveIndex(
            model_name='client',
            name='main_client_created_850ce2_idx',
        ),
        migrations.RenameIndex(
            model_name='client',
            new_name='food_safety_client__a6d82c_idx',
            old_name='main_client_client__8da953_idx',
        ),
        migrations.RenameIndex(
            model_name='client',
            new_name='food_safety_name_be0e7e_idx',
            old_name='main_client_name_c070b5_idx',
        ),
        migrations.AddField(
            model_name='client',
            name='internal_account_code',
            field=models.CharField(blank=True, help_text='From Google Sheets Column H', max_length=100, null=True, verbose_name='Internal Account Code'),
        ),
        migrations.AddField(
            model_name='client',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Client Name'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['internal_account_code'], name='food_safety_interna_923e6c_idx'),
        ),
        migrations.AlterModelTable(
            name='client',
            table='food_safety_agency_clients',
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['inspector'], name='main_inspec_inspect_e6d693_idx'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['inspection_date'], name='main_inspec_inspect_e7e732_idx'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['facility_client_name'], name='main_inspec_facilit_21fee2_idx'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['town'], name='main_inspec_town_2a466d_idx'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['commodity'], name='main_inspec_commodi_0a5d35_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inspection',
            unique_together={('inspector', 'inspection_number')},
        ),
        migrations.DeleteModel(
            name='Shipment',
        ),
    ]
