# Generated by Django 5.1.7 on 2025-10-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_add_additional_email_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodsafetyagencyinspection',
            name='approved_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('YES', 'Yes')], default='PENDING', help_text='Approval status for this inspection group', max_length=10, null=True),
        ),
    ]
