# Generated by Django 5.1.7 on 2025-08-30 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_inspection_remove_shipment_client_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodSafetyAgencyInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity', models.CharField(blank=True, help_text='Commodity type (e.g., POULTRY, RAW, PMP, EGGS)', max_length=50, null=True)),
                ('date_of_inspection', models.DateField(blank=True, help_text='Date of inspection', null=True)),
                ('start_of_inspection', models.TimeField(blank=True, help_text='Start time of inspection', null=True)),
                ('end_of_inspection', models.TimeField(blank=True, help_text='End time of inspection', null=True)),
                ('inspection_location_type_id', models.IntegerField(blank=True, help_text='Inspection location type ID', null=True)),
                ('is_direction_present_for_this_inspection', models.BooleanField(default=False, help_text='Direction present for this inspection')),
                ('inspector_id', models.IntegerField(blank=True, help_text='Inspector ID from remote system', null=True)),
                ('inspector_name', models.CharField(blank=True, help_text='Human-readable inspector name', max_length=100, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, help_text='GPS Latitude', max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, help_text='GPS Longitude', max_digits=11, null=True)),
                ('is_sample_taken', models.BooleanField(default=False, help_text='Was sample taken during inspection')),
                ('inspection_travel_distance_km', models.DecimalField(blank=True, decimal_places=2, help_text='Travel distance in kilometers', max_digits=8, null=True)),
                ('remote_id', models.IntegerField(blank=True, help_text='Original ID from remote system', null=True)),
                ('client_name', models.CharField(blank=True, help_text='Client name from remote system', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Food Safety Agency Inspection',
                'verbose_name_plural': 'Food Safety Agency Inspections',
                'db_table': 'food_safety_agency_inspections',
                'ordering': ['-date_of_inspection', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Claim_No', models.CharField(max_length=100, unique=True, verbose_name='Shipment Number')),
                ('client_reference', models.CharField(blank=True, help_text='Auto-generated client-specific reference (e.g., ClientName-1-20250601)', max_length=50, null=True, verbose_name='Client Reference')),
                ('Brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='Brand')),
                ('Claimant', models.CharField(blank=True, max_length=200, null=True, verbose_name='Claimant Name')),
                ('Intent_To_Claim', models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3, null=True, verbose_name='Intent To Claim')),
                ('Intend_Claim_Date', models.DateField(blank=True, null=True, verbose_name='Intent To Claim Date')),
                ('Formal_Claim_Received', models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3, null=True, verbose_name='Formal Claim')),
                ('Formal_Claim_Date_Received', models.DateField(blank=True, null=True, verbose_name='Formal Claim Date')),
                ('Claimed_Amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Value')),
                ('Amount_Paid_By_Carrier', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Paid By Carrier')),
                ('Amount_Paid_By_Awa', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Paid By ISCM/AWA')),
                ('Amount_Paid_By_Insurance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Paid By Insurance')),
                ('Total_Savings', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Total Savings')),
                ('Financial_Exposure', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Financial Exposure')),
                ('Settlement_Status', models.CharField(blank=True, choices=[('SETTLED', 'Settled'), ('NOT_SETTLED', 'Not Settled'), ('PARTIAL', 'Partially Settled')], max_length=15, null=True, verbose_name='Settled or Not Settled')),
                ('Status', models.CharField(choices=[('OPEN', 'Open'), ('PENDING', 'Pending'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected'), ('UNDER_REVIEW', 'Under Review')], default='OPEN', max_length=15, verbose_name='Status')),
                ('Closed_Date', models.DateField(blank=True, null=True, verbose_name='Closed Date')),
                ('Branch', models.CharField(choices=[('ATL', 'ATL'), ('CMU', 'CMU'), ('CON', 'CON'), ('DOR', 'DOR'), ('HEC', 'HEC'), ('HNL', 'HNL'), ('HOU', 'HOU'), ('ICS', 'ICS'), ('IMP', 'IMP'), ('JFK', 'JFK'), ('LCL', 'LCL'), ('ORD', 'ORD'), ('PPG', 'PPG')], max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shipment',
                'verbose_name_plural': 'Shipments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='inspection',
            name='main_inspec_inspect_e6d693_idx',
        ),
        migrations.RemoveIndex(
            model_name='inspection',
            name='main_inspec_inspect_e7e732_idx',
        ),
        migrations.RemoveIndex(
            model_name='inspection',
            name='main_inspec_facilit_21fee2_idx',
        ),
        migrations.RemoveIndex(
            model_name='inspection',
            name='main_inspec_town_2a466d_idx',
        ),
        migrations.RemoveIndex(
            model_name='inspection',
            name='main_inspec_commodi_0a5d35_idx',
        ),
        migrations.AlterUniqueTogether(
            name='inspection',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='additional_email_1',
            field=models.EmailField(blank=True, help_text='Additional email contact 1', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='additional_email_2',
            field=models.EmailField(blank=True, help_text='Additional email contact 2', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='additional_email_3',
            field=models.EmailField(blank=True, help_text='Additional email contact 3', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='additional_email_4',
            field=models.EmailField(blank=True, help_text='Additional email contact 4', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='compiled_supporting_documents',
            field=models.BooleanField(default=False, help_text='Supporting documents compiled'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='compliance_document',
            field=models.BooleanField(default=False, help_text='Compliance document required'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='verification_external_testing',
            field=models.BooleanField(default=False, help_text='External testing verification required'),
        ),
        migrations.AlterModelTable(
            name='inspection',
            table='inspections',
        ),
        migrations.AddIndex(
            model_name='foodsafetyagencyinspection',
            index=models.Index(fields=['commodity'], name='food_safety_commodi_c598e6_idx'),
        ),
        migrations.AddIndex(
            model_name='foodsafetyagencyinspection',
            index=models.Index(fields=['date_of_inspection'], name='food_safety_date_of_d2c2d7_idx'),
        ),
        migrations.AddIndex(
            model_name='foodsafetyagencyinspection',
            index=models.Index(fields=['inspector_name'], name='food_safety_inspect_3f44db_idx'),
        ),
        migrations.AddIndex(
            model_name='foodsafetyagencyinspection',
            index=models.Index(fields=['client_name'], name='food_safety_client__f07db9_idx'),
        ),
        migrations.AddIndex(
            model_name='foodsafetyagencyinspection',
            index=models.Index(fields=['inspector_id'], name='food_safety_inspect_a2643c_idx'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='main.client'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['Claim_No'], name='main_shipme_Claim_N_a03a13_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['client'], name='main_shipme_client__17eb8e_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['Status'], name='main_shipme_Status_7826b6_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['Branch'], name='main_shipme_Branch_16242a_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['client_reference'], name='main_shipme_client__85a5d7_idx'),
        ),
    ]
