# Generated by Django 5.1.7 on 2025-10-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_foodsafetyagencyinspection_approved_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodsafetyagencyinspection',
            name='approved_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved')], default='PENDING', help_text='Approval status for this inspection group', max_length=10, null=True),
        ),
    ]
