# Generated by Django 5.1.7 on 2025-10-30 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_update_yes_to_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodsafetyagencyinspection',
            name='comment',
            field=models.TextField(blank=True, help_text='Comment for this inspection group', null=True),
        ),
    ]
