# Generated by Django 5.1.7 on 2025-08-31 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_add_settings_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name'], 'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterField(
            model_name='foodsafetyagencyinspection',
            name='is_sample_taken',
            field=models.BooleanField(blank=True, help_text='Was sample taken during inspection', null=True),
        ),
    ]
