# Generated by Django 5.1.7 on 2025-08-31 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_client_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodsafetyagencyinspection',
            name='latitude',
            field=models.CharField(blank=True, help_text='GPS Latitude', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='foodsafetyagencyinspection',
            name='longitude',
            field=models.CharField(blank=True, help_text='GPS Longitude', max_length=20, null=True),
        ),
    ]
