# Generated by Django 5.1.7 on 2025-10-30 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_foodsafetyagencyinspection_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='foodsafetyagencyinspection',
            name='occurrence_uploaded_by',
            field=models.ForeignKey(blank=True, help_text='User who uploaded Occurrence document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrence_uploads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='foodsafetyagencyinspection',
            name='occurrence_uploaded_date',
            field=models.DateTimeField(blank=True, help_text='Date when Occurrence document was uploaded', null=True),
        ),
    ]
