# Generated by Django 5.1.7 on 2025-08-31 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_foodsafetyagencyinspection_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='sync_interval_unit',
            field=models.CharField(choices=[('minutes', 'Minutes'), ('hours', 'Hours'), ('days', 'Days')], default='hours', help_text='Sync interval unit', max_length=10),
        ),
        migrations.AlterField(
            model_name='settings',
            name='sync_interval',
            field=models.IntegerField(default=24, help_text='Sync interval value'),
        ),
    ]
