# Generated by Django 5.1.7 on 2025-11-01 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_add_occurrence_tracking_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='foodsafetyagencyinspection',
            name='composition_uploaded_by',
            field=models.ForeignKey(blank=True, help_text='User who uploaded Composition document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='composition_uploads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='foodsafetyagencyinspection',
            name='composition_uploaded_date',
            field=models.DateTimeField(blank=True, help_text='Date when Composition document was uploaded', null=True),
        ),
        migrations.AlterField(
            model_name='foodsafetyagencyinspection',
            name='occurrence_uploaded_by',
            field=models.ForeignKey(blank=True, help_text='User who uploaded Accurance document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrence_uploads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='foodsafetyagencyinspection',
            name='occurrence_uploaded_date',
            field=models.DateTimeField(blank=True, help_text='Date when Accurance document was uploaded', null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='occurrence_report',
            field=models.BooleanField(default=False, help_text='Accurance report required'),
        ),
    ]
