# Generated by Django 5.1.7 on 2025-08-31 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_settings_sync_interval_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='dark_mode',
            field=models.BooleanField(default=False, help_text='Enable dark mode theme'),
        ),
    ]
