# Generated by Django 5.1.7 on 2025-11-03 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_foodsafetyagencyinspection_composition_uploaded_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodsafetyagencyinspection',
            old_name='lab_uploaded_by',
            new_name='coa_uploaded_by',
        ),
        migrations.RenameField(
            model_name='foodsafetyagencyinspection',
            old_name='lab_uploaded_date',
            new_name='coa_uploaded_date',
        ),
        migrations.AlterField(
            model_name='foodsafetyagencyinspection',
            name='coa_uploaded_by',
            field=models.ForeignKey(blank=True, help_text='User who uploaded COA document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coa_uploads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='foodsafetyagencyinspection',
            name='coa_uploaded_date',
            field=models.DateTimeField(blank=True, help_text='Date when COA document was uploaded', null=True),
        ),
    ]
