# Generated by Django 5.1.7 on 2025-08-31 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_settings_dark_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
