# Generated by Django 5.1.7 on 2025-11-07 06:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_lab_to_coa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='foodsafetyagencyinspection',
            name='internal_account_code',
            field=models.CharField(blank=True, db_index=True, help_text='Internal Account Code from SQL Server (used to match with Google Sheets)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodsafetyagencyinspection',
            name='client_name',
            field=models.CharField(blank=True, help_text='Client name (updated from Google Sheets if match found)', max_length=200, null=True),
        ),
        migrations.AddIndex(
            model_name='foodsafetyagencyinspection',
            index=models.Index(fields=['internal_account_code'], name='food_safety_interna_887892_idx'),
        ),
    ]
