# Generated by Django 5.1.7 on 2025-11-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_add_internal_account_code_to_inspections'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.IntegerField(db_index=True, verbose_name='Client ID')),
                ('facility_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Facility Type')),
                ('group_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Group Type')),
                ('commodity', models.CharField(blank=True, max_length=100, null=True, verbose_name='Commodity')),
                ('province', models.CharField(blank=True, max_length=100, null=True, verbose_name='Province')),
                ('corporate_group', models.CharField(blank=True, max_length=200, null=True, verbose_name='Corporate Group')),
                ('other', models.CharField(blank=True, max_length=200, null=True, verbose_name='Other')),
                ('internal_account_code', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Internal Account Code')),
                ('allocated', models.BooleanField(default=False, verbose_name='Allocated')),
                ('eclick_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='E-Click Name')),
                ('representative_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Representative Email Address')),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone Number')),
                ('duplicates', models.CharField(blank=True, max_length=200, null=True, verbose_name='Duplicates')),
                ('active_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Active/Deactive')),
                ('last_synced', models.DateTimeField(auto_now=True, verbose_name='Last Synced')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Client Allocation',
                'verbose_name_plural': 'Client Allocations',
                'db_table': 'client_allocation',
                'ordering': ['client_id'],
                'indexes': [models.Index(fields=['client_id'], name='client_allo_client__1c9a77_idx'), models.Index(fields=['internal_account_code'], name='client_allo_interna_7a7f26_idx'), models.Index(fields=['allocated'], name='client_allo_allocat_9083ec_idx')],
            },
        ),
    ]
