# Generated by Django 5.1.7 on 2025-11-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_clientallocation'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='clientallocation',
            new_name='idx_client_id',
            old_name='client_allo_client__1c9a77_idx',
        ),
        migrations.RenameIndex(
            model_name='clientallocation',
            new_name='idx_account_code',
            old_name='client_allo_interna_7a7f26_idx',
        ),
        migrations.RenameIndex(
            model_name='clientallocation',
            new_name='idx_allocated',
            old_name='client_allo_allocat_9083ec_idx',
        ),
        migrations.AlterField(
            model_name='clientallocation',
            name='commodity',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Commodity'),
        ),
        migrations.AlterField(
            model_name='clientallocation',
            name='facility_type',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Facility Type'),
        ),
        migrations.AlterField(
            model_name='clientallocation',
            name='group_type',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Group Type'),
        ),
        migrations.AddIndex(
            model_name='clientallocation',
            index=models.Index(fields=['facility_type'], name='idx_facility_type'),
        ),
        migrations.AddIndex(
            model_name='clientallocation',
            index=models.Index(fields=['commodity'], name='idx_commodity'),
        ),
        migrations.AddIndex(
            model_name='clientallocation',
            index=models.Index(fields=['facility_type', 'commodity'], name='idx_facility_commodity'),
        ),
        migrations.AddIndex(
            model_name='clientallocation',
            index=models.Index(fields=['allocated', 'facility_type'], name='idx_alloc_facility'),
        ),
        migrations.AddIndex(
            model_name='clientallocation',
            index=models.Index(fields=['last_synced'], name='idx_last_synced'),
        ),
        migrations.AddIndex(
            model_name='clientallocation',
            index=models.Index(fields=['client_id', 'allocated', 'facility_type'], name='idx_list_view'),
        ),
        migrations.AddConstraint(
            model_name='clientallocation',
            constraint=models.CheckConstraint(condition=models.Q(('client_id__gt', 0)), name='client_id_positive'),
        ),
    ]
