# Generated by Django 5.1.7 on 2025-08-31 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_client_client_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodsafetyagencyinspection',
            name='calcium',
            field=models.BooleanField(default=False, help_text='Calcium testing required'),
        ),
        migrations.AddField(
            model_name='foodsafetyagencyinspection',
            name='dna',
            field=models.BooleanField(default=False, help_text='DNA testing required'),
        ),
        migrations.AddField(
            model_name='foodsafetyagencyinspection',
            name='fat',
            field=models.BooleanField(default=False, help_text='Fat testing required'),
        ),
        migrations.AddField(
            model_name='foodsafetyagencyinspection',
            name='protein',
            field=models.BooleanField(default=False, help_text='Protein testing required'),
        ),
    ]
