# Generated by Django 5.1.7 on 2025-08-31 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_foodsafetyagencyinspection_calcium_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('CREATE', 'Create Record'), ('UPDATE', 'Update Record'), ('DELETE', 'Delete Record'), ('VIEW', 'View Page'), ('NAVIGATE', 'Navigate'), ('SYNC', 'Data Sync'), ('SETTINGS', 'Settings Change'), ('USER_MANAGEMENT', 'User Management'), ('PASSWORD_RESET', 'Password Reset'), ('FILE_UPLOAD', 'File Upload'), ('EXPORT', 'Data Export'), ('IMPORT', 'Data Import'), ('SEARCH', 'Search'), ('FILTER', 'Filter'), ('ERROR', 'Error'), ('WARNING', 'Warning'), ('INFO', 'Information')], max_length=50, verbose_name='Action Type')),
                ('page', models.CharField(blank=True, max_length=100, null=True, verbose_name='Page/URL')),
                ('object_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Object Type')),
                ('object_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Object ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('details', models.JSONField(blank=True, null=True, verbose_name='Additional Details')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'System Log',
                'verbose_name_plural': 'System Logs',
                'db_table': 'system_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user'], name='system_logs_user_id_85bc8b_idx'), models.Index(fields=['action'], name='system_logs_action_04fbd3_idx'), models.Index(fields=['timestamp'], name='system_logs_timesta_84e60c_idx'), models.Index(fields=['page'], name='system_logs_page_1e22af_idx'), models.Index(fields=['object_type'], name='system_logs_object__209485_idx')],
            },
        ),
    ]
