# Generated by Django 5.1.7 on 2025-11-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_add_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodsafetyagencyinspection',
            name='invoice_number',
            field=models.CharField(blank=True, help_text='Invoice number assigned to this inspection', max_length=100, null=True),
        ),
    ]
