# Generated by Django 5.1.7 on 2025-12-03 07:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_add_invoice_number_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='foodsafetyagencyinspection',
            unique_together={('commodity', 'remote_id')},
        ),
        migrations.AddIndex(
            model_name='foodsafetyagencyinspection',
            index=models.Index(fields=['commodity', 'remote_id'], name='food_safety_commodi_57531f_idx'),
        ),
    ]
