# Generated by Django 5.1.7 on 2025-08-31 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_systemlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodsafetyagencyinspection',
            name='needs_retest',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], help_text='Whether this inspection needs retesting', max_length=3, null=True, verbose_name='Needs Retest'),
        ),
    ]
