# Generated by Django 5.1.7 on 2025-08-31 21:24

from django.db import migrations


def set_retest_no_for_no_sample(apps, schema_editor):
    """Set needs_retest to 'NO' for all inspections where no sample was taken"""
    FoodSafetyAgencyInspection = apps.get_model('main', 'FoodSafetyAgencyInspection')
    
    # Update all inspections where is_sample_taken is False or None
    inspections_to_update = FoodSafetyAgencyInspection.objects.filter(
        is_sample_taken__in=[False, None]
    )
    
    # Set needs_retest to 'NO' for these inspections
    updated_count = inspections_to_update.update(needs_retest='NO')
    print(f"Updated {updated_count} inspections to set needs_retest='NO' for no sample taken")


def reverse_set_retest_no_for_no_sample(apps, schema_editor):
    """Reverse the data migration - set needs_retest back to None"""
    FoodSafetyAgencyInspection = apps.get_model('main', 'FoodSafetyAgencyInspection')
    
    # Set needs_retest back to None for inspections where no sample was taken
    inspections_to_revert = FoodSafetyAgencyInspection.objects.filter(
        is_sample_taken__in=[False, None]
    )
    
    # Set needs_retest back to None
    reverted_count = inspections_to_revert.update(needs_retest=None)
    print(f"Reverted {reverted_count} inspections to set needs_retest=None")


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_foodsafetyagencyinspection_needs_retest'),
    ]

    operations = [
        migrations.RunPython(
            set_retest_no_for_no_sample,
            reverse_set_retest_no_for_no_sample
        ),
    ]
