# Generated by Django 5.1.7 on 2025-09-02 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_set_retest_no_for_no_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodsafetyagencyinspection',
            name='hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Manual entry of hours worked', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='foodsafetyagencyinspection',
            name='km_traveled',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Manual entry of kilometers traveled', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='foodsafetyagencyinspection',
            name='lab',
            field=models.CharField(blank=True, choices=[('lab_a', 'Lab A'), ('lab_b', 'Lab B'), ('lab_c', 'Lab C'), ('lab_d', 'Lab D'), ('lab_e', 'Lab E')], help_text='Laboratory used for testing', max_length=20, null=True),
        ),
    ]
