# Generated by Django 5.1.7 on 2025-09-02 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_foodsafetyagencyinspection_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectorMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspector_id', models.IntegerField(help_text='Server inspector ID (e.g., 1234567)', unique=True)),
                ('inspector_name', models.CharField(help_text='Human-readable inspector name (e.g., Ethan)', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this inspector is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Inspector Mapping',
                'verbose_name_plural': 'Inspector Mappings',
                'db_table': 'inspector_mappings',
                'ordering': ['inspector_name'],
                'indexes': [models.Index(fields=['inspector_id'], name='inspector_m_inspect_d0ffe1_idx'), models.Index(fields=['inspector_name'], name='inspector_m_inspect_46f912_idx')],
            },
        ),
    ]
