# Generated by Django 5.1.7 on 2025-09-02 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_inspectormapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodsafetyagencyinspection',
            name='bought_sample',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Value of bought sample in Rand (ZAR)', max_digits=10, null=True),
        ),
    ]
