# Generated by Django 5.2.4 on 2025-09-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_foodsafetyagencyinspection_bought_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodsafetyagencyinspection',
            name='product_class',
            field=models.CharField(blank=True, help_text='Product class/category', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='foodsafetyagencyinspection',
            name='product_name',
            field=models.CharField(blank=True, help_text='Product name (e.g., Mince, Burger, Boerewors)', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='foodsafetyagencyinspection',
            name='lab',
            field=models.CharField(blank=True, choices=[('lab_a', 'Lab A'), ('lab_b', 'Lab B'), ('lab_c', 'Lab C'), ('lab_d', 'Lab D'), ('lab_e', 'Lab E'), ('lab_f', 'Lab F')], help_text='Laboratory used for testing', max_length=20, null=True),
        ),
    ]
