# Generated by Django 5.1.7 on 2025-12-12 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_systemsettings_sync_interval_hours_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='actual_behavior',
            field=models.TextField(blank=True, help_text='What actually happened', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='additional_notes',
            field=models.TextField(blank=True, help_text='Any other relevant details', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='affected_area',
            field=models.CharField(blank=True, help_text='Affected module/area of the system', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='browser_info',
            field=models.CharField(blank=True, help_text='Browser/device information', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='expected_behavior',
            field=models.TextField(blank=True, help_text='What should happen', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='impact_users',
            field=models.CharField(blank=True, help_text='Number of affected users', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_blocking',
            field=models.CharField(blank=True, help_text='Is this blocking work?', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='issue_type',
            field=models.CharField(blank=True, help_text='Type of issue (bug, feature, question, etc.)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='steps_to_reproduce',
            field=models.TextField(blank=True, help_text='Steps to reproduce the issue', null=True),
        ),
    ]
