# Generated by Django 5.1.7 on 2025-12-13 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_ticket_actual_behavior_ticket_additional_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionfee',
            name='rate',
            field=models.DecimalField(decimal_places=2, help_text='Current fee rate amount (always reflects latest rate)', max_digits=10),
        ),
        migrations.CreateModel(
            name='FeeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, help_text='Historical fee rate', max_digits=10)),
                ('effective_date', models.DateField(help_text='Date when this rate becomes/became active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this history record was created')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about why the fee was changed', null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this fee version', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='main.inspectionfee')),
            ],
            options={
                'verbose_name': 'Fee History',
                'verbose_name_plural': 'Fee Histories',
                'db_table': 'inspection_fee_history',
                'ordering': ['-effective_date', '-created_at'],
                'indexes': [models.Index(fields=['fee', '-effective_date'], name='idx_fee_effective_date'), models.Index(fields=['effective_date'], name='idx_effective_date')],
                'unique_together': {('fee', 'effective_date')},
            },
        ),
    ]
