# Generated by Django 5.2.4 on 2025-09-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_foodsafetyagencyinspection_product_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='compliance_auto_sync',
            field=models.BooleanField(default=False, help_text='Enable automatic compliance document syncing'),
        ),
        migrations.AddField(
            model_name='settings',
            name='compliance_batch_size',
            field=models.IntegerField(default=50, help_text='Number of inspections to process per batch'),
        ),
        migrations.AddField(
            model_name='settings',
            name='compliance_date_range',
            field=models.IntegerField(default=7, help_text='Process inspections from last N days'),
        ),
        migrations.AddField(
            model_name='settings',
            name='compliance_sync_interval',
            field=models.IntegerField(default=5, help_text='Compliance sync interval value'),
        ),
        migrations.AddField(
            model_name='settings',
            name='compliance_sync_unit',
            field=models.CharField(choices=[('minutes', 'Minutes'), ('hours', 'Hours'), ('days', 'Days')], default='minutes', help_text='Compliance sync interval unit', max_length=10),
        ),
    ]
