# Generated by Django 5.2.4 on 2025-09-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_settings_compliance_auto_sync_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='compliance_batch_mode',
            field=models.CharField(choices=[('batch', 'Process in Batches'), ('all', 'Process ALL at Once')], default='batch', help_text='Processing mode: batches or all documents at once', max_length=20),
        ),
        migrations.AlterField(
            model_name='settings',
            name='compliance_batch_size',
            field=models.IntegerField(default=50, help_text='Number of inspections to process per batch (only for batch mode)'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='compliance_date_range',
            field=models.IntegerField(default=7, help_text='Process inspections from last N days (only for batch mode)'),
        ),
    ]
