# Generated by Django 5.1.7 on 2025-12-13 18:38

from django.db import migrations
from datetime import date


def populate_initial_fee_history(apps, schema_editor):
    """
    Create initial FeeHistory records for all existing InspectionFee entries.
    This establishes a baseline so we have historical data starting from today.
    """
    InspectionFee = apps.get_model('main', 'InspectionFee')
    FeeHistory = apps.get_model('main', 'FeeHistory')

    # Get today's date as the effective date for all existing fees
    effective_date = date.today()

    # For each existing fee, create a history record with its current rate
    for fee in InspectionFee.objects.all():
        # Only create if no history exists for this fee
        if not FeeHistory.objects.filter(fee=fee).exists():
            FeeHistory.objects.create(
                fee=fee,
                rate=fee.rate,
                effective_date=effective_date,
                created_by=fee.updated_by,  # Use the same user who last updated the fee
                notes="Initial fee history record created during migration"
            )


def reverse_populate_fee_history(apps, schema_editor):
    """
    Remove all FeeHistory records created by this migration.
    This allows the migration to be reversed if needed.
    """
    FeeHistory = apps.get_model('main', 'FeeHistory')
    FeeHistory.objects.filter(
        notes="Initial fee history record created during migration"
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_add_fee_history_model'),
    ]

    operations = [
        migrations.RunPython(
            populate_initial_fee_history,
            reverse_code=reverse_populate_fee_history
        ),
    ]
