# Generated by Django 5.2.4 on 2025-09-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_add_compliance_batch_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, help_text='From Google Sheets Column K', max_length=254, null=True, verbose_name='Client Email'),
        ),
    ]
