# Generated by Django 5.2.4 on 2025-09-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_add_client_email_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='manual_email',
            field=models.EmailField(blank=True, help_text='Manually added email that persists across syncs', max_length=254, null=True, verbose_name='Manual Email Override'),
        ),
    ]
