# Generated by Django 5.2.4 on 2025-09-03 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_add_manual_email_override'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_emails', to='main.client')),
            ],
            options={
                'db_table': 'food_safety_agency_client_emails',
                'indexes': [models.Index(fields=['email'], name='food_safety_email_273f98_idx'), models.Index(fields=['client'], name='food_safety_client__cff284_idx')],
            },
        ),
    ]
