# Generated by Django 5.1.7 on 2025-09-03 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_add_client_additional_emails'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_sync_enabled', models.BooleanField(default=False, verbose_name='Enable Auto Sync')),
                ('backup_frequency_days', models.IntegerField(default=7, verbose_name='Backup Frequency (days)')),
                ('session_timeout_minutes', models.IntegerField(default=30, verbose_name='Session Timeout (minutes)')),
                ('google_sheets_enabled', models.BooleanField(default=True, verbose_name='Google Sheets Integration')),
                ('sql_server_enabled', models.BooleanField(default=True, verbose_name='SQL Server Integration')),
                ('sync_interval_hours', models.IntegerField(default=24, verbose_name='Sync Interval (hours)')),
                ('compliance_sync_enabled', models.BooleanField(default=True, verbose_name='Enable Automatic Compliance Sync')),
                ('compliance_sync_interval_hours', models.IntegerField(default=5, verbose_name='Compliance Sync Interval (hours)')),
                ('compliance_processing_mode', models.CharField(choices=[('all_at_once', 'Process ALL at Once'), ('incremental', 'Incremental Processing'), ('manual', 'Manual Processing Only')], default='all_at_once', max_length=20, verbose_name='Processing Mode')),
                ('onedrive_enabled', models.BooleanField(default=True, verbose_name='OneDrive Integration')),
                ('theme_mode', models.CharField(choices=[('light', 'Light Mode'), ('dark', 'Dark Mode'), ('auto', 'Auto')], default='light', max_length=10, verbose_name='Theme Mode')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
