# Generated by Django 5.1.7 on 2026-01-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodsafetyagencyinspection',
            name='is_manual',
            field=models.BooleanField(default=False, help_text='True if this inspection was manually entered (not synced from SQL Server)'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='auto_sync_enabled',
            field=models.BooleanField(default=True, help_text='Background sync is ALWAYS enabled to prevent data loss', verbose_name='Enable Auto Sync'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='google_sheets_enabled',
            field=models.BooleanField(default=True, help_text='Always syncs - field kept for compatibility', verbose_name='Google Sheets Integration'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='sql_server_enabled',
            field=models.BooleanField(default=True, help_text='Always syncs - field kept for compatibility', verbose_name='SQL Server Integration'),
        ),
    ]
