# Generated by Django 5.2.4 on 2025-09-04 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='onedrive_auto_sync',
            field=models.BooleanField(default=True, verbose_name='Enable Auto Sync'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='onedrive_cache_days',
            field=models.IntegerField(default=60, verbose_name='Cache Duration (Days)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='onedrive_local_caching',
            field=models.BooleanField(default=True, verbose_name='Enable Local File Caching'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='onedrive_sync_interval_hours',
            field=models.IntegerField(default=2, verbose_name='Sync Interval (Hours)'),
        ),
    ]
