# Generated by Django 5.2.4 on 2025-09-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_systemsettings_onedrive_auto_sync_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodsafetyagencyinspection',
            name='is_sent',
            field=models.BooleanField(default=False, help_text='Whether documents have been sent to client'),
        ),
        migrations.AddField(
            model_name='foodsafetyagencyinspection',
            name='sent_date',
            field=models.DateTimeField(blank=True, help_text='Date when documents were sent', null=True),
        ),
    ]
