# Generated by Django 5.2.4 on 2025-09-09 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_add_sent_status_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='foodsafetyagencyinspection',
            name='invoice_uploaded_by',
            field=models.ForeignKey(blank=True, help_text='User who uploaded Invoice document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_uploads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='foodsafetyagencyinspection',
            name='invoice_uploaded_date',
            field=models.DateTimeField(blank=True, help_text='Date when Invoice was uploaded', null=True),
        ),
        migrations.AddField(
            model_name='foodsafetyagencyinspection',
            name='rfi_uploaded_by',
            field=models.ForeignKey(blank=True, help_text='User who uploaded RFI document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfi_uploads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='foodsafetyagencyinspection',
            name='rfi_uploaded_date',
            field=models.DateTimeField(blank=True, help_text='Date when RFI was uploaded', null=True),
        ),
    ]
