# Generated by Django 5.2.4 on 2025-09-09 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_add_upload_tracking_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='foodsafetyagencyinspection',
            name='sent_by',
            field=models.ForeignKey(blank=True, help_text='User who marked documents as sent', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_inspections', to=settings.AUTH_USER_MODEL),
        ),
    ]
