# Generated by Django 5.2.4 on 2025-09-11 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_add_sent_by_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodsafetyagencyinspection',
            name='onedrive_folder_id',
            field=models.CharField(blank=True, help_text='OneDrive folder ID where files are stored', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='foodsafetyagencyinspection',
            name='onedrive_upload_date',
            field=models.DateTimeField(blank=True, help_text='Date when files were uploaded to OneDrive', null=True),
        ),
        migrations.AddField(
            model_name='foodsafetyagencyinspection',
            name='onedrive_uploaded',
            field=models.BooleanField(default=False, help_text='Whether files have been uploaded to OneDrive'),
        ),
    ]
