# Generated by Django 5.2.4 on 2025-09-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_add_onedrive_tracking_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='onedrive_upload_delay_days',
            field=models.IntegerField(default=3, verbose_name='Upload Delay (Days)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='onedrive_upload_delay_unit',
            field=models.CharField(choices=[('hours', 'Hours'), ('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months'), ('years', 'Years')], default='days', max_length=10, verbose_name='Upload Delay Unit'),
        ),
    ]
