# Generated by Django 5.2.4 on 2025-09-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_systemsettings_onedrive_upload_delay_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='compliance_daily_sync_enabled',
            field=models.BooleanField(default=True, verbose_name='Enable Daily Compliance Sync'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='compliance_last_processed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Compliance Process Date'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='compliance_skip_processed',
            field=models.BooleanField(default=True, verbose_name='Skip Already Processed Documents'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='priority_1_interval',
            field=models.IntegerField(default=1, verbose_name='First 2 Months Refresh Interval'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='priority_1_unit',
            field=models.CharField(default='hours', max_length=10, verbose_name='First 2 Months Unit'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='priority_2_interval',
            field=models.IntegerField(default=2, verbose_name='Last 2 Months Refresh Interval'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='priority_2_unit',
            field=models.CharField(default='hours', max_length=10, verbose_name='Last 2 Months Unit'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='compliance_processing_mode',
            field=models.CharField(choices=[('all_at_once', 'Process ALL at Once'), ('incremental', 'Incremental Processing'), ('manual', 'Manual Processing Only')], default='incremental', max_length=20, verbose_name='Processing Mode'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='compliance_sync_interval_hours',
            field=models.IntegerField(default=24, verbose_name='Compliance Sync Interval (hours)'),
        ),
    ]
