# Generated by Django 5.1.7 on 2025-09-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_systemsettings_compliance_daily_sync_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='sync_interval_hours',
            field=models.FloatField(default=24.0, verbose_name='Sync Interval (hours)'),
        ),
    ]
